language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install -U pip
  - pip install coveralls
  - pip install -e git+https://github.com/rockho-team/shuup.git@master#egg=shuup[everything]
  - pip install -r requirements.txt
  - pip install -e .
script:
  - py.test -ra -vvv --cov-config .coveragerc --cov shuup_correios shuup_correios_tests
after_success: coveralls
