language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -U pip
  - pip install coveralls
# install shoop's master HEAD - v4.0 compatible
  - pip install -e git+https://github.com/shoopio/shoop.git#egg=shoop[everything]
  - pip install -e .
script:
  - py.test -ra -vvv --cov-config .coveragerc --cov shoop_correios shoop_correios_tests
after_success: coveralls
